---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (Ubuntu)
    tags: ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Updates (RHEL)
    tags: rhel
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RHEL"

- hosts: webservers
  become: true
  tasks:
  - name: copy file
    copy:
      src: ./myfiles/def_home.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'
      backup: yes


  - name: Set fact for Debian
    tags: 
      - apache
      - httpd
      - php
    set_fact:
      webvar: "apache2"
      weblib: "libapache2-mod-php"
    when: ansible_os_family == "Debian"

  - name: Set fact for RedHat
    tags: 
      - apache
      - httpd
      - php
    set_fact:
      webvar: "httpd"
      weblib: "php"
    when: ansible_os_family == "RedHat"
  
  - name: install apache and php pkg
    tags: 
      - apache
      - httpd
      - php
    package:
      name:
        - "{{ webvar }}"
        - "{{ weblib }}"
      state: latest
      update_cache: yes
