---

- hosts: webservers
  become: true
  tasks:

  - name: install apache and php pkg
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
