---

- hosts: webservers
  become: true
  tasks:

  - name: update apt cache
    apt:
      update_cache: yes
    when: ansible_distribution in ['Ubuntu', 'Debian']

  - name: install apache and php pkg
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ['Ubuntu', 'Debian']
