---

- hosts: webservers
  become: true
  tasks:

  - name: update apt cache
    apt:
      update_cache: yes
    when: ansible_distribution in ['Ubuntu', 'Debian']

  - name: install apache pkg
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ['Ubuntu', 'Debian']

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ['Ubuntu', 'Debian']
